# Use Microsoft's DevContainer Go image
FROM mcr.microsoft.com/devcontainers/go:1.22

# Set up work directory
WORKDIR /workspace

# Copy the current directory contents into the container
COPY . /workspace

# # Ensure Go dependencies are installed
# RUN go mod tidy

# Default command
CMD ["bash"]
